name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}} 
        OC_USERNAME: ${{secrets.OC_USERNAME}}
        OC_PASSWORD: ${{secrets.OC_PASSWORD}}     
      run: |
        docker build -t image:v1 --file dockerfiledb .
        /usr/local/bin/oc login -u $OC_USERNAME -p $OC_PASSWORD --insecure-skip-tls-verify=true
        docker login -u $DOCKER_USERNAME -p $(oc whoami -t) default-route-openshift-image-registry.apps.ocp4.6.eidikointernal.com
        /usr/local/bin/ && ./oc project manoj1
        docker tag image:v1 default-route-openshift-image-registry.apps.ocp4.6.eidikointernal.com/manoj1/devopsimage:v1
        docker push default-route-openshift-image-registry.apps.ocp4.6.eidikointernal.com/manoj1/devopsimage:v1
        /home/bandaru/Downloads/devshift.sh
