name: Maven CI with Nexus IQ

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/https://github.com/manojawsdevops/Devops_RakCICD.git@main
      with:
        serverUrl: http://localhost:8085/repository/maven-releases/
        username: admin
        password: ${{ secrets.NEXUS_PASSWORD }}
        applicationId: sample-maven
        stage: Build
        target: ./target/
