name: Nexus

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: http://localhost:8085/repository/devops_cicd/
        username: admin
        password: ${{ secrets.NEXUS_PASSWORD }}
        stage: Build
        target: ./target/
