name: Maven CI with Nexus IQ

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: http://localhost:8085/repository/maven-releases/
        username: admin
        password: ${{ secrets.NEXUS_PASSWORD }}
        stage: Build
        target: ./target/
