name: Java and Nexus Repository Publisher

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://192.168.2.40:8085/repository/devops_cicd/
        username: admin
        password: ${{ secrets.NEXUS_PASSWORD }}
        format: raw
        repository: devops_cicd
        coordinates: groupId=org.apache.maven artifactId=Application1
        assets: extension=bar 
        filename: /home/bandaru/Music/Application1.bar
