name: sonarqube_scanning

on: push

jobs:
 SonarQubeTrigger:
     name: SonarQube_Scanner
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@master
     - name: SonarQube_Scan
       uses: kitabisa/sonarqube-action@master
       with:
          host: ${{ secrets.SONAR_HOST }}
          login: ${{ secrets.SONAR_TOKEN}}
          projectBaseDir: "Application1"
          projectKey: "Devops_RakCICD"
          projectName: "Devops_RakCICD"
          projectVersion: "v0.0.1"
  
       
        

        
       

