name: sonarqube_scanning

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        host: ${{ secrets.SONAR_HOST }}
        login: ${{ secrets.SONAR_TOKEN }}
        sonar.scm.provider: =git
        sonar.projectKey: =Application1
        sonar.projectName: =Application1
        sonar.projectVersion: =1.0
        sonar.sourceEncoding: =UTF-8
        projectBaseDir: "/root/Aplication1"
       
        

        
       

