name: sonarqube_scanning

on: push

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        host: ${{ secrets.SONAR_HOST }}
        login: ${{ secrets.SONAR_TOKEN }}
        projectBaseDir: "$WORKSPACE"
        projectKey: "sonarqube"
        projectName: "sonarqube"
        projectVersion: "v0.0.1"

